### PR TITLE
Unique username issue fixed

### PR DESCRIPTION
**Pull request by aviwar**

### CODE REVIEW

**Comment by chaitak-gorai** [comment]
I have reviewed the code it is working fine. The user is registered to the database if a username exists.
But there are some minor changes to do
- Check the emailjs send form which sends a mail to us when a user is registered. At present, it is sending mail by checking the "validate form" only. 
- Second, don't clear the form if the username exists.

**Comment by chaitak-gorai** [comment]
Also, we know the code is very ugly for registration.php. If you can clean the code a bit and add some comments too about what the functions doing, it will be most welcomed. 
Thank you:)

**Review by aviwar — COMMENTED** [review]
@chaitak-gorai Code changed as per comments. Kindly check it.

**Comment by chaitak-gorai** [comment]
You have done a great job. We appreciate your contribution.
Thank you! Keep Contributing:)

**Pull request merged**
