### PR TITLE
Feature: Add link 'View Profile' in ad_navigation as dropdown-menu of 'Profile'

### PR DESCRIPTION
**Pull request by kaiquegarcia**
There's a page with the URL `/user.php?u_id=<user's id>`, but none of the menus from admin navigation pointed to this. So I changed the "Profile" menu to be a dropdown with the options "Update profile" (pointing to `admin/profile.php`) and "View profile" (pointing to the URL we're talking about).

This PR is related to issue #55

### CODE REVIEW

**Comment by chaitak-gorai** [comment]
Ok, that's cool. I revied the code and it's working fine.
just one more thing to add:
There is no "back" option on the user profile page. we have to click on admin to go back to admin.
If you can add a "go back" which will take back to admin it will be a better user experience.

**Comment by kaiquegarcia** [comment]
Do you have any preferences about the button's appearance?

**Comment by chaitak-gorai** [comment]
> Do you have any preferences about the button's appearance?

No such preference. It should be simple and clear. Also, it should be responsible for mobile devices. Use bootstrap classes for that.
Thank You!

**Comment by chaitak-gorai** [comment]
> @chaitak-gorai Check out my idea, what do you think?

Some suggestion:

- Move the position  to top right 
- increase the size of the button a bit
- add bootstrap classes for better ui.

**Comment by kaiquegarcia** [comment]
@chaitak-gorai Hey, I'm using the bootstrap classes already without any CSS changes, but I needed to put a margin on it now, can you take a look?

I think it feels like Windows programs (but with a single action haha)

**Comment by chaitak-gorai** [comment]
That's cool. 
I think it is now looking good.

**Pull request merged**
