### PR TITLE
Like feature for posts added

### PR DESCRIPTION
**Pull request by kristonela**
Like button with counter added to each post 
- post_likes_count column with default value 0 added into db

### CODE REVIEW

**Comment by chaitak-gorai** [comment]
Give some time to review the code. Thanks for keeping patience.

**Comment by chaitak-gorai** [comment]
Hello @kristonela sorry for the delay in reviewing the code. 
The like button is not working correctly. It is not updating the likes also it acts as an input field. I am sharing the snipe.
You kindly review your code again and do the necessary changes.
Thank you
likes

**Comment by kristonela** [comment]
I'm sure it worked when i pulled the request .. but I will check it again. 

Odoslané z iPhonu

**Comment by kristonela** [comment]
Hello, I fixed the input field, I checked the like button for a million times, it works just fine ... I 'm sure it is all as it is supposed to be and functional. Thank you for checking it :)

**Comment by chaitak-gorai** [comment]
hello @kristonela sorry but the like button is not working. it is not adding likes to the post.

**Comment by kristonela** [comment]
As you can see, it DOES Work ... i believe there must be issue in commit or something

**Comment by chaitak-gorai** [comment]
@kristonela it is not functioning in the post.

**Comment by kristonela** [comment]
Can you send me some details of what is happening ? I sent you a video that it is working for me so I would like to find where is the problem. Odoslané z aplikácie Pošta pre Windows Od: Chaitak GoraiOdoslané: pondelok 22. novembra 2021 18:46Komu: chaitak-gorai/blogbookKópia: Kristonela; MentionPredmet: Re: [chaitak-gorai/blogbook] Like feature for posts added (PR ***@***.*** it is not functioning in the post.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  



	
		
			
				
			
		
		
			
				Táto správa bola skontrolovaná na prítomnosť vírusov programom Avast Antivirus.
				www.avast.com

**Pull request merged**
