### PR TITLE
fix blog post summary acting as link

### PR DESCRIPTION
**Pull request by pdejan**
This should do it if I understood issue correctly which was to fix blog content preview acting as link/read more.

### CODE REVIEW

**Comment by chaitak-gorai** [comment]
@pdejan I think you have mistaken the issue.
The summary will act as a link, just we have to remove text decoration (underline) on hover.

**Comment by pdejan** [comment]
> @pdejan I think you have mistaken the issue. The summary will act as a link, just we have to remove text decoration (underline) on hover.

I figured that might be the case after I've removed it as link :) Will go back and fix it.

**Comment by pdejan** [comment]
It's been fixed as intended now.

**Comment by chaitak-gorai** [comment]
That's great!
This issue is already solve the commit 7ab6839bf234fac817593fffc70617a620ff62e8 for index.php 
But there are some more places to change:
We need to update the same for "category.php" ie when the posts cards are shown category-wise.
.
Do the necessary changes and we will then merge the code at once.
Thank You!

**Comment by pdejan** [comment]
> That's great! This issue is already solve the commit [7ab6839](https://github.com/chaitak-gorai/blogbook/commit/7ab6839bf234fac817593fffc70617a620ff62e8) for index.php But there are some more places to change: We need to update the same for "category.php" ie when the posts cards are shown category-wise. . Do the necessary changes and we will then merge the code at once. Thank You!

My commit did fix issue for "category.php" in first place, also latest commit fixed issue referenced here #23 (remove text decoration from Top Blog Post in sidebar)

**Comment by chaitak-gorai** [comment]
> > That's great! This issue is already solve the commit [7ab6839](https://github.com/chaitak-gorai/blogbook/commit/7ab6839bf234fac817593fffc70617a620ff62e8) for index.php But there are some more places to change: We need to update the same for "category.php" ie when the posts cards are shown category-wise. . Do the necessary changes and we will then merge the code at once. Thank You!
> 
> My commit did fix issue for "category.php" in first place, also latest commit fixed issue referenced here #23 (remove text decoration from Top Blog Post in sidebar)

That's Cool. I have reviewed the code and it has solved both the issue.

**Comment by chaitak-gorai** [comment]
@pdejan Please add your name and profile link to [contributors.md](https://github.com/chaitak-gorai/blogbook/blob/main/contributors.md)
Thank you Keep Contributing:)

**Pull request merged**
